Combine

diff --git a/.github/workflows/Build mod.yml b/.github/workflows/Build mod.yml
--- a/.github/workflows/Build mod.yml
+++ b/.github/workflows/Build mod.yml
@@ -1,4 +1,4 @@
-name: Build and Release
+name: Build, Release, and Version Check
 
 permissions:
   contents: write
@@ -11,6 +11,27 @@ on:
     branches: [ "master" ]
 
 jobs:
+  check:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Get version from manifest
+        shell: bash
+        run: |
+          version_number=$(jq -r '.version_number' manifest.json)
+          echo "VERSIONNUM=$version_number" >> $GITHUB_ENV
+          echo "Version number is $version_number"
+
+      - name: Check .csproj
+        shell: bash
+        run: |
+          version_number=$(sed -nE 's/.*<VersionPrefix>([^<]+)<\/VersionPrefix>.*/\1/p' HealthDisplayWithFont/HealthDisplayWithFont.csproj)
+          if [ "$version_number" != "$VERSIONNUM" ]; then
+            echo "Error: got version $version_number, expected $VERSIONNUM"
+            exit 1
+          fi
+
   build:
     runs-on: windows-latest
 
